---
- name: Check if partition are already mounted
  shell: df | grep "{{item.partition}}" | wc -l
  with_items:
    - "{{kfebs_vol}}"
  register: kfebs_checked

- name: Make filesystem
  filesystem: fstype=ext4 dev="{{item.item.partition}}" force=no
  when: "{{item.stdout}} == 0"
  with_items: kfebs_checked.results

- name: Mount the partition
  mount: src="{{item.item.partition}}" dest="{{item.item.mountpoint}}"
  when: "{{item.stdout}} == 0"
  with_items: kfebs_checked.results
